// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXZ4fNks15gs-6V8glfmG4fepcXma1KjY',
    appId: '1:147725350696:web:d0e4ed6c156ac36567821d',
    messagingSenderId: '147725350696',
    projectId: 'comandas-flutter',
    authDomain: 'comandas-flutter.firebaseapp.com',
    storageBucket: 'comandas-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNZ3C6I5rvj_BQmutvgXHvAwOAhjhNUa8',
    appId: '1:147725350696:android:74b9bfcbcc2244e667821d',
    messagingSenderId: '147725350696',
    projectId: 'comandas-flutter',
    storageBucket: 'comandas-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhZ4cA46UL8tXPHYrR8JstliyE2f8zFnY',
    appId: '1:147725350696:ios:7e54adb92ff97f3f67821d',
    messagingSenderId: '147725350696',
    projectId: 'comandas-flutter',
    storageBucket: 'comandas-flutter.appspot.com',
    iosClientId: '147725350696-2a44lra02qj91hc3b026q9r17qe50fsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.comandasFlutterGit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhZ4cA46UL8tXPHYrR8JstliyE2f8zFnY',
    appId: '1:147725350696:ios:b5d1f4fa8443844267821d',
    messagingSenderId: '147725350696',
    projectId: 'comandas-flutter',
    storageBucket: 'comandas-flutter.appspot.com',
    iosClientId: '147725350696-icrd58g0aj1tdb4fpm7n6i6dl2ji7m51.apps.googleusercontent.com',
    iosBundleId: 'com.example.comandasFlutterGit.RunnerTests',
  );
}
